server:
  port: 8080

spring:
  #profile 설정
  profiles:
    active: local # ${server.profile:local} <-- 이래 쓰는 거랑 뭐가 달라요 ?

  web:
    resources:
      add-mappings: false

  servlet:
    multipart:
      maxFileSize: 1MB
      maxRequestSize: 1MB

  #  # google
  #  mail:
  #    host: smtp.gmail.com
  #    port: 587
  #    username: ililil9412@gmail.com
  #    password: ${google.key:password}
  #    properties:
  #      mail:
  #        smtp:
  #          auth: true
  #          starttls:
  #            enable: true
  #            required: true
logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    root: info
    com.doyeon.puppy: info

api-prefix: /api
#docs:/api/docs/index.html


# 'spring-boot-security-jwt-moyeon-puppy' | base64
jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LW1veWVvbi1wdXBweQ== #local

--- #local
logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    root: info
    com.doyeon.puppy: debug

spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none  #절대 수정 금지
    #      format_sql: true
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        default_batch_size: 100

  datasource:
    url: jdbc:mysql://localhost:3306/securitydy?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: redis
      port: 6379
